In [36]:
import numpy as np
import pandas as pd

In [37]:
one_dimensional_array = np.array([1, 2, 3, 4, 5])
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
tensor_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [38]:
print("One-dimensional array:")
print(one_dimensional_array)
print("\nTwo-dimensional array:")
print(two_dimensional_array)
print("\nTensor array:")
print(tensor_array)


One-dimensional array:
[1 2 3 4 5]

Two-dimensional array:
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]

Tensor array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
two_dimensional_array.ndim

2

In [40]:
two_dimensional_array.shape

(2, 3)

In [41]:
two_dimensional_array.size

6

In [42]:
zero_array = np.zeros((3, 4), dtype=int)
print(zero_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [43]:
one_array = np.ones((2, 3), dtype=float)
print(one_array) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [44]:
array_range = np.arange(1, 13).reshape(3, 4)
array_range

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
array_range[0,0]

np.int64(1)

In [46]:
array_list = [[1, 2, 3], [4, 5, 6]]
array_list [0][0]

1

In [47]:
array_range * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [48]:
np.sqrt(array_range)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [49]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A + B:")
A + B
print("\nA - B:")
A - B

A + B:

A - B:


array([[-4, -4],
       [-4, -4]])

In [50]:
A * B

array([[ 5, 12],
       [21, 32]])

In [51]:
A@B

array([[19, 22],
       [43, 50]])

In [52]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
A.T

array([[1, 3],
       [2, 4]])

In [55]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [56]:
A = np.array([[1, 2,3], [3, 4, 5], [5, 6,7]])

In [57]:
np.linalg.det(A)

np.float64(0.0)

##PANDAS


In [58]:
df_data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
})
df_data

,Name,Age,City
0,Alice,25,New York
1,Bob,30,Los Angeles
2,Charlie,35,Chicago


In [59]:
df_data.shape

(3, 3)

In [ ]:
df_data.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [61]:
df_data.dtypes

Name      str
Age     int64
City      str
dtype: object

In [62]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      int64
 2   City    3 non-null      str  
dtypes: int64(1), str(2)
memory usage: 204.0 bytes


In [64]:
df_data.describe(include='all')

,Name,Age,City
count,3,3.0,3
unique,3,NaN,3
top,Alice,NaN,New York
freq,1,NaN,1
mean,NaN,30.0,NaN
std,NaN,5.0,NaN
min,NaN,25.0,NaN
25%,NaN,27.5,NaN
50%,NaN,30.0,NaN
75%,NaN,32.5,NaN


In [65]:
df_github = pd.read_csv('projects_github.csv')

In [66]:
df_github.info()

<class 'pandas.DataFrame'>
RangeIndex: 3462 entries, 0 to 3461
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3462 non-null   str  
 1   year     3462 non-null   int64
 2   quarter  3462 non-null   int64
 3   count    3462 non-null   int64
dtypes: int64(3), str(1)
memory usage: 108.3 KB


In [68]:
df_github.describe(include='all')

,name,year,quarter,count
count,3462,3462.000000,3462.000000,3462.000000
unique,187,NaN,NaN,NaN
top,Ruby,NaN,NaN,NaN
freq,43,NaN,NaN,NaN
mean,NaN,2017.013576,2.502022,11131.740901
std,NaN,2.552447,1.122835,34686.780996
min,NaN,2011.000000,1.000000,100.000000
25%,NaN,2015.000000,1.000000,230.000000
50%,NaN,2017.000000,2.000000,616.500000
75%,NaN,2019.000000,4.000000,3380.500000


In [87]:
projects_2022 = df_github[df_github['year'] == 2021]
projects_2022

,name,year,quarter,count
3107,Python,2021,1,193698
3108,JavaScript,2021,1,188179
3109,Java,2021,1,123189
3110,TypeScript,2021,1,92310
3111,Go,2021,1,89986
...,...,...,...,...
3443,Raku,2021,4,113
3444,Pascal,2021,4,105
3445,Nim,2021,4,102
3446,QML,2021,4,102


In [85]:
df_github.nunique()

name        187
year         12
quarter       4
count      2051
dtype: int64

In [ ]:
df_movies = pd.read_csv('imdb_top_1000.csv')

In [89]:
df_movies.describe(include='all')

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
count,1000,1000,1000,899,1000,1000,1000.000000,1000,843.000000,1000,1000,1000,1000,1000,1.000000e+03,831
unique,1000,999,100,16,140,202,NaN,1000,NaN,548,660,841,891,939,NaN,823
top,https://m.media-amazon.com/images/M/MV5BMDFkYT...,Drishyam,2014,U,130 min,Drama,NaN,Two imprisoned men bond over a number of years...,NaN,Alfred Hitchcock,Tom Hanks,Emma Watson,Rupert Grint,Michael Caine,NaN,"4,360,000"
freq,1,2,32,234,23,85,NaN,1,NaN,14,12,7,5,4,NaN,5
mean,NaN,NaN,NaN,NaN,NaN,NaN,7.949300,NaN,77.971530,NaN,NaN,NaN,NaN,NaN,2.736929e+05,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,0.275491,NaN,12.376099,NaN,NaN,NaN,NaN,NaN,3.273727e+05,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,7.600000,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,2.508800e+04,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.700000,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,5.552625e+04,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,7.900000,NaN,79.000000,NaN,NaN,NaN,NaN,NaN,1.385485e+05,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,8.100000,NaN,87.000000,NaN,NaN,NaN,NaN,NaN,3.741612e+05,NaN


In [90]:
df_movies.isna().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [91]:
df_github.columns

Index(['name', 'year', 'quarter', 'count'], dtype='str')

In [92]:
df_github.groupby('name').size()

name
1C Enterprise     2
ABAP             16
AGS Script        1
API Blueprint     6
ASP               6
                 ..
Zephir            1
mIRC Script      25
nesC              9
ooc               9
q                 3
Length: 187, dtype: int64

In [93]:
df_github.groupby('year').size().sort_values(ascending=False).head(10)

year
2016    479
2017    468
2018    396
2015    396
2019    382
2020    364
2021    341
2014    284
2013    194
2012    124
dtype: int64

In [96]:
df_github.pivot_table(index='year', values='name', aggfunc='count').sort_values(by='name', ascending=False).head(10)

,name
year,
2016,479
2017,468
2018,396
2015,396
2019,382
2020,364
2021,341
2014,284
2013,194
